---
# tasks file for Apache

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: check for SElinux
  command: getenforce
  register: sestatus
  changed_when: false

