---
# tasks file for Docker
#- name: DOCKER | Installing Docker to a RHEL/CentOS 6 machine
#  include: redhat6.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

#- name: DOCKER | Installing Docker to a RHEL/CentOS 7 machine
#  include: redhat7.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: DOCKER | Installing Docker to a Debian/Ubuntu machine
  include: debian.yml
  when: ansible_os_family == "Debian"

