---
# tasks file for php
- name: install PHP on Redhat/CentOS machine
  yum: name={{ item }} state=present
  with_items: 
  - php
  - php-mysql
  when: ansible_os_family == "RedHat"

- name: install PHP on Debina/Ubuntu machine
  apt: name={{ item }} state=present
  with_items:
  - php5
  - php5-mysql
  - libapache2-mod-php5 
  - libapache2-mod-auth-mysql
  - php5-mcrypt
  when: ansible_os_family == "Debian"

- name: config SElinux to allow HTTP server to connect to DB
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0

- name: set proxy configurations for GIT when behind a FW
  command: git config --global http.proxy http://192.168.89.32:11111/
# change your proxy server IP address and port

- name: clean www previous content from Apache installation 
  command: rm -fr /var/www/html

- name: copy code from REPO
  git: repo={{ repository }} version={{ webapp_version }} dest=/var/www/html force=yes
