---
# tasks file for nginx
- name: NGINX | Installing NGINX repo rpm
  include: redhat.yml
  when: ansible_os_family == "RedHat"
 
- name: NGINX | Installing NGINX
  include: debian.yml
  when: ansible_os_family == "Debian"

- name: copy www content
  include: copy-www-content.yml
