---
- name: install Redhat Development Tools
  yum: name="@Development tools" state=present update_cache=yes
  when: ansible_os_family == "RedHat"

- name: install Debian Development Tools
  apt: name=build-essential state=present update_cache=yes
  when: ansible_os_family == "Debian"

